#!/bin/sh

set -e

CURRENTDIR="$(cd "${0%/*}" && echo "$PWD")"
APPDIR=${APPDIR:-SHARUN_DIR}
MAIN_BIN="$(awk -F'=| ' '/^Exec=/{print $2; exit}' "$CURRENTDIR"/*.desktop)"
MAIN_BIN="${MAIN_BIN##*/}"
BIN="${ARGV0:-$0}"
BIN="${BIN##*/}"
unset ARGV0
SHAREDIR="${XDG_DATA_HOME:-$HOME/.local/share}"
DBUS_SERVICE="${SHAREDIR}"/dbus-1/services/org.gnome.Calculator.SearchProvider.service

# successful(ish) attempt to integrate search into Gnome Shell
if [ -n "$APPIMAGE" ] && command -v gnome-shell 1>/dev/null; then
	mkdir -p "${SHAREDIR}"/dbus-1/services/
	mkdir -p "${SHAREDIR}"/gnome-shell/search-providers/
	echo '[D-BUS Service]' > "$DBUS_SERVICE"
	echo 'Name=org.gnome.Calculator.SearchProvider' >> "$DBUS_SERVICE"
	echo "Exec=$APPIMAGE gnome-calculator-search-provider" >> "$DBUS_SERVICE"
	cp "${CURRENTDIR}"/share/gnome-shell/search-providers/org.gnome.Calculator-search-provider.ini \
		"${SHAREDIR}"/gnome-shell/search-providers/
fi

# Check if there's $1 supplied as binary, then ARGV0, then main bin
if [ -f "$CURRENTDIR"/bin/"$1" ] && [ "$1" = "gnome-calculator-search-provider" ]; then
	BIN="$1"
    shift
	exec "$CURRENTDIR"/bin/"$BIN" "$@"
elif [ -f "$CURRENTDIR"/bin/"$BIN" ]; then
	exec "$CURRENTDIR"/bin/"$BIN" "$@"
elif [ -f "$CURRENTDIR"/bin/"$1" ]; then
	BIN="$1"
	shift
	exec "$CURRENTDIR"/bin/"$BIN" "$@"
else
	exec "$CURRENTDIR"/bin/"$MAIN_BIN" "$@"
fi
